 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingsys;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
import busbookingsys.AdminUpdate;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Anirudh
 */
public class AdminValidation extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;

    /**
     * Creates new form AdminValidation
     */
    public AdminValidation() {
        initComponents();
       conn=dbConnection.connect();
    }
       
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernm = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        user1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loagin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 550));
        getContentPane().setLayout(null);

        usernm.setBackground(new java.awt.Color(204, 204, 204));
        usernm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernm.setText("User Name:");
        usernm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernm.setOpaque(true);
        getContentPane().add(usernm);
        usernm.setBounds(240, 200, 106, 40);

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setText("Password:");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.setOpaque(true);
        getContentPane().add(password);
        password.setBounds(240, 280, 114, 39);

        user1.setBackground(new java.awt.Color(204, 204, 204));
        user1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        getContentPane().add(user1);
        user1.setBounds(410, 200, 260, 38);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(216, 93, 293, 0);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Login Page");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 10, 740, 73);

        loagin.setBackground(new java.awt.Color(204, 204, 204));
        loagin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loagin.setText("Login");
        loagin.setBorder(new javax.swing.border.MatteBorder(null));
        loagin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loaginMouseClicked(evt);
            }
        });
        loagin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaginActionPerformed(evt);
            }
        });
        getContentPane().add(loagin);
        loagin.setBounds(80, 462, 177, 41);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(367, 462, 177, 41);

        Password.setBackground(new java.awt.Color(204, 204, 204));
        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Password);
        Password.setBounds(410, 280, 257, 40);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.setToolTipText("");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(400, 360, 120, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\anihk\\Downloads\\java_project\\bus6.png")); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 170, 200, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\anihk\\Downloads\\java_project\\bo2.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 830, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void loaginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaginActionPerformed
        // TODO add your handling code here:
        String username=user1.getText();
        String pass=Password.getText();
        
        AdminLogin ad=new AdminLogin();
       ad.setVisible(true);
       this.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_loaginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginAdminCustomer ls = new LoginAdminCustomer();
        ls.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            Password.setEchoChar((char)0);
        }else{
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void loaginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaginMouseClicked
        // TODO add your handling code here:
        if(user1==null || Password==null){
            JOptionPane.showMessageDialog(null,"Some fields are empty");
        }
        else{
            try{
                
                pst=conn.prepareStatement("select*from adminupdate where    Name=? and Password=?");
                pst.setString(1, user1.getText());
                pst.setString(2, Password.getText());
                rs=pst.executeQuery();
                if(rs.next()){
                    
                     JOptionPane.showMessageDialog(null,"Login Success");
                      user1.setText(null);
    Password.setText(null);
     AdminLogin ad=new AdminLogin();
       ad.setVisible(true);
       this.setVisible(true);
       this.setVisible(false);
 
     dispose();               
                }
                else{
                     JOptionPane.showMessageDialog(null,"Invalid name or password");
                     Password.setText(null);
    user1.setText(null);
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_loaginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminValidation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loagin;
    private javax.swing.JLabel password;
    private javax.swing.JTextField user1;
    private javax.swing.JLabel usernm;
    // End of variables declaration//GEN-END:variables
}
