/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingsys;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anirudh
 */
public class AdminUpdate extends javax.swing.JFrame {

    /**
     * Creates new form AddBus
     */
    public AdminUpdate() {
        initComponents();
        Connect();
        
    }


      
     PreparedStatement psd;
       PreparedStatement psd1;
       java.sql.Connection con;
       ResultSet rs;
       private void Connect()  {
        try {
            // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
             
               con =  DriverManager.getConnection("jdbc:mysql://localhost/super","root","");
               
            } catch (SQLException ex) {
                Logger.getLogger(BookSeat.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookSeat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Loader()
        {
            String Name = text.getText();
            String Password = pass.getText();
        try {

            psd = con.prepareStatement("select * from  adminUpdate");
           
          rs =psd.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c =rsd.getColumnCount();
            DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                     
                for(int i=1;i<=c;i++)
                {
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("Password"));
                   
                    
                }
                d.addRow(v2);
            }
                
            }
            
        catch (SQLException ex) {
            Logger.getLogger(BookSeat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"no buses available");
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ShowButton = new javax.swing.JButton();
        text = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Admin Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 106, 49));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 106, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Admin Update :-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 0, 285, 49));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 75, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Remove");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 80, 30));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 360, 180));

        ShowButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ShowButton.setText("Show");
        ShowButton.setBorder(new javax.swing.border.MatteBorder(null));
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 80, 30));

        text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, 30));

        pass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 1030, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//   TODO add your handling code here:
 // String name1=text.getText();
  //String pass2=pass.getText();
    //DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
//    String []toadd={name,pass};
  //  dt.addRow(toadd);
    //text.setText("");
    //pass.setText("");

 String Name = text.getText();
            String Password = pass.getText();
            
            if(Name.equals("")&&Password.equals("")){
            
                JOptionPane.showMessageDialog(this, "Please Enter UserName and Password");
                
            }
            
            else if(!(Name.equals(""))&&Password.equals("")){
                JOptionPane.showMessageDialog(this,"Please Enter Password");
            }
            else if(Name.equals("")&&!(Password.equals(""))){
                JOptionPane.showMessageDialog(this,"Please Enter Name");
            }
            else{   
                  try {
                     psd =con.prepareStatement("insert into adminupdate (Name,Password) values(?,?)");
                     psd.setString(1, Name);
                      psd.setString(2, Password); 
                      psd.executeUpdate();
                      Loader();
                       JOptionPane.showMessageDialog(this,"Admin Added Succesfully");
                     } catch (SQLException ex) {
                      Logger.getLogger(AdditonBus.class.getName()).log(Level.SEVERE, null, ex);
                             JOptionPane.showMessageDialog(this,"Password already exists");
                     }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Name = text.getText();
            String Password = pass.getText();
            if(Name.equals("")&&Password.equals("")){
            
                JOptionPane.showMessageDialog(this, "Please Enter UserName and Password");
                
            }
           
            
            
            else if(Name.equals("")&&!(Password.equals(""))){
                JOptionPane.showMessageDialog(this,"Please Enter Name");
            }
            else{
        String user=text.getText();
        
       AdminLogin ad=new AdminLogin();
       ad.setVisible(true);
       this.setVisible(true);
       this.setVisible(false);
       
       ad.username(user);
       
       dispose();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
         int index=jTable1.getSelectedRow();
            text.setText(dt.getValueAt(index,0).toString());
            pass.setText(dt.getValueAt(index,1).toString());

    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
   //      DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
    // int index=jTable1.getSelectedRow();
      //   dt.removeRow(index);
         // text.setText("");
          //pass.setText("");
String Name = text.getText();
            String Password = pass.getText();
        try {
            psd =con.prepareStatement("delete from adminupdate  where Password=?");
            
            psd.setString(1, Password); 
            psd.executeUpdate();
            Loader();
            JOptionPane.showMessageDialog(this,"Admin Removed");
        } catch (SQLException ex) {
            Logger.getLogger(AdditonBus.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this,"error");
        }
                                          

    }//GEN-LAST:event_jButton2ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        Loader();
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pass;
    public static javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
