/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingsys;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.print.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
/**
 *
 * @author Joseph Raj Vishal
 */
public class BookBus extends javax.swing.JFrame {

    HashMap<String, Integer> hash_map=new HashMap<>();
    
    public void FillComboBox()
    {
        hash_map.put("--Select--", null);
        hash_map.put("AC", 5000);
        hash_map.put("Non AC", 4000);
        hash_map.put("Sleeper", 3000);
        hash_map.put("Seater", 2000);
        hash_map.put("Luxury", 8000);
        hash_map.put("Volvo", 6000);
        for(Map.Entry entry: hash_map.entrySet())
        {
            Object Items = entry.getKey();
            bustype.addItem((String)Items);
        }
    }
    double name,aadhar,source,dest,type,cost;
    /**
     * Creates new form BookBus
     */
    public BookBus() {
        initComponents();
        FillComboBox();
        bustype.setSelectedItem(null);
        price1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bustype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panel_print = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.MatteBorder(null));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(210, 310, 143, 62);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aadhar");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 120, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 120, 27);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Price");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 120, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Source");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 120, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Book Bus ");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 308, 143, 62);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 18, 140, 30);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 60, 140, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bus Type");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 210, 120, 27);

        bustype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bustype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "AC", "Non AC", "Sleeper", "Seater", "Luxury", "Volvo", " ", " " }));
        bustype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bustype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bustypeActionPerformed(evt);
            }
        });
        getContentPane().add(bustype);
        bustype.setBounds(210, 210, 140, 27);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Destination");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 120, 27);

        price.setBackground(new java.awt.Color(153, 255, 153));
        price.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(price);
        price.setBounds(180, 268, 118, 0);

        price1.setEditable(false);
        price1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        getContentPane().add(price1);
        price1.setBounds(210, 250, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 10, 390, 320);

        panel_print.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_print.setText("Print");
        panel_print.setBorder(new javax.swing.border.MatteBorder(null));
        panel_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panel_printActionPerformed(evt);
            }
        });
        getContentPane().add(panel_print);
        panel_print.setBounds(700, 340, 70, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangalore", "Mangalore", "Hampi", "Coorg", "Halebeedu", "Mysore", "Srirangapatna", "Malgudi", "Jog Falls", "Shivmogga", "Mulliyana Giri", "Hassan", "Bijapur", "Badami", "St.Mary's Island", "Kudremukh", "Gulbarga", "Ooty", "Pattadakal", "Udupi" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 110, 140, 30);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangalore", "Mangalore", "Chitradurga", "Bagalkot", "Udupi", "Mysore", "Raichur", "Hassan", "Belgam" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(210, 160, 140, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\anihk\\Downloads\\java_project\\bus7.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 810, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BookSB sb = new BookSB();
        sb.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed
/*edited by H anirudh*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this,"success");
        
        
        
      String Name=String.format(jTextField2.getText());
       String Aadhar=String.format(jTextField3.getText());
        String Source=String.format(jComboBox1.getSelectedItem().toString());
         String destination=String.format(jComboBox2.getSelectedItem().toString());
         String Bustype = bustype.getSelectedItem().toString();
          String price=String.format(price1.getText());
       //=====================================================
       int refs=1325 +(int) (Math.random()*4238);
       //int ref=(refs);
       //==================================================
          Calendar timer=Calendar.getInstance();
          timer.getTime();
          SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
          tTime.format(timer.getTime());
          SimpleDateFormat Tdate=new SimpleDateFormat("dd-MM-yyyy");
          Tdate.format(timer.getTime());
        //================================================
        jTextArea1.append("\t            Details of the Customer\n" +
        "    Reference:\t" +refs+
                "\n==============================================\t " +
                
                "\n==============================================\t " +
               "\n   Customer Name:\t" +Name +
                "\n   Aadhar:\t\t" +Aadhar +
                "\n   Source:\t\t" +Source +
                "\n   Destination:\t\t" +destination +
                "\n   Bustype:\t\t" +Bustype +
                "\n   Price:\t\t" +price +
                "\n=============================================\t" +
                "\n Date: " +Tdate.format(timer.getTime())+
                  "\tTime: " +tTime.format(timer.getTime()) +
                "\n\n\tThank you for Booking\n" );
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bustypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bustypeActionPerformed
        // TODO add your handling code here:
       String ItemName=(String)bustype.getSelectedItem();
       price1.setText(String.valueOf(hash_map.get(ItemName)));
    }//GEN-LAST:event_bustypeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_formWindowActivated

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed

    private void panel_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panel_printActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(1.3,2.6);
                
                jTextArea1.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_panel_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bustype;
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton panel_print;
    private javax.swing.JLabel price;
    private javax.swing.JTextField price1;
    // End of variables declaration//GEN-END:variables
}
