/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingsys;

/**
 *
 * @author Jigyasa Gupta
 */
public class LoginAdminCustomer extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdminCustomer
     */
    
    public LoginAdminCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBtn = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Banner = new javax.swing.JLabel();
        CustomerBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 630));
        getContentPane().setLayout(null);

        AdminBtn.setBackground(new java.awt.Color(102, 102, 255));
        AdminBtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        AdminBtn.setText("Admin Login");
        AdminBtn.setToolTipText("");
        AdminBtn.setBorder(new javax.swing.border.MatteBorder(null));
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AdminBtn);
        AdminBtn.setBounds(310, 150, 331, 99);

        Logout.setBackground(new java.awt.Color(153, 153, 255));
        Logout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("");
        Logout.setBorder(new javax.swing.border.MatteBorder(null));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(310, 500, 340, 82);

        Banner.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        Banner.setForeground(new java.awt.Color(102, 0, 102));
        Banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Banner.setText("Welcome To The Bus Reservation System");
        Banner.setBorder(new javax.swing.border.MatteBorder(null));
        Banner.setOpaque(true);
        getContentPane().add(Banner);
        Banner.setBounds(23, 13, 841, 92);

        CustomerBtn1.setBackground(new java.awt.Color(153, 153, 255));
        CustomerBtn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        CustomerBtn1.setText("Customer Login");
        CustomerBtn1.setToolTipText("");
        CustomerBtn1.setBorder(new javax.swing.border.MatteBorder(null));
        CustomerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerBtn1);
        CustomerBtn1.setBounds(310, 320, 331, 95);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\anihk\\Downloads\\java_project\\bus10.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here
     this.setVisible(false);
      
    }//GEN-LAST:event_LogoutActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        // TODO add your handling code here:
       
          AdminValidation av = new AdminValidation();
       av.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void CustomerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerBtn1ActionPerformed
        // TODO add your handling code here:
        BookSB sb = new BookSB();
     sb.setVisible(true);
     this.setVisible(false);
     
    }//GEN-LAST:event_CustomerBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdminCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdminCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdminCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdminCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdminCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JLabel Banner;
    private javax.swing.JButton CustomerBtn1;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
