/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingsys;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anirudh
 */
public class RemoveBus extends javax.swing.JFrame {

    /**
     * Creates new form RemoveBus
     */
    public RemoveBus() {
        initComponents();
        Connect();
        
    }
     PreparedStatement psd;
       java.sql.Connection con;
       private void Connect()  {
        try {
            // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
             
               con =  DriverManager.getConnection("jdbc:mysql://localhost/super","root","");
               
            } catch (SQLException ex) {
                Logger.getLogger(BookSeat.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(this,"error PAGE");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"error PAGE");
            Logger.getLogger(BookSeat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remove = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        remover = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 380));
        getContentPane().setLayout(null);

        remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remove.setText("Remove");
        remove.setBorder(new javax.swing.border.MatteBorder(null));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove);
        remove.setBounds(37, 194, 73, 31);

        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(new javax.swing.border.MatteBorder(null));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(180, 190, 70, 31);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remove Bus");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 47);

        remover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(remover);
        remover.setBounds(60, 110, 156, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\anihk\\Downloads\\java_project\\bus1.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 40, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
          AdminLogin ad=new AdminLogin();
       ad.setVisible(true);
       this.setVisible(true);
       this.setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        try {
            // TODO add your handling code here:
            String rem = remover.getText();
            psd= con.prepareStatement( " DELETE FROM busid WHERE busno=?");
            psd.setString(1, rem);
            psd.executeUpdate();
             JOptionPane.showMessageDialog(this,"suceesfull submission");
            
        } catch (SQLException ex) {
            Logger.getLogger(RemoveBus.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(this,"this bus id doesnt exist");
        }
    }//GEN-LAST:event_removeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton remove;
    private javax.swing.JTextField remover;
    // End of variables declaration//GEN-END:variables
}
